app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['middleware' => ['web']], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');

    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth.checkrole:admin'], function () {
        //**CATEGORIES**//
        Route::get('categories', ['as' => 'categories.index', 'uses' => 'CategoriesController@index']);
        Route::get('categories/create', ['as' => 'categories.create', 'uses' => 'CategoriesController@create']);
        Route::get('categories/edit/{id}', ['as' => 'categories.edit', 'uses' => 'CategoriesController@edit']);
        Route::post('categories/store', ['as' => 'categories.store', 'uses' => 'CategoriesController@store']);
        Route::put('categories/update/{id}', ['as' => 'categories.update', 'uses' => 'CategoriesController@update']);
        //**CLIENTS**//
        Route::get('clients', ['as' => 'clients.index', 'uses' => 'ClientsController@index']);
        Route::get('clients/create', ['as' => 'clients.create', 'uses' => 'ClientsController@create']);
        Route::get('clients/edit/{id}', ['as' => 'clients.edit', 'uses' => 'ClientsController@edit']);
        Route::post('clients/store', ['as' => 'clients.store', 'uses' => 'ClientsController@store']);
        Route::put('clients/update/{id}', ['as' => 'clients.update', 'uses' => 'ClientsController@update']);
        //**PRODUCTS**//
        Route::get('products', ['as' => 'products.index', 'uses' => 'ProductsController@index']);
        Route::get('products/create', ['as' => 'products.create', 'uses' => 'ProductsController@create']);
        Route::get('products/edit/{id}', ['as' => 'products.edit', 'uses' => 'ProductsController@edit']);
        Route::post('products/store', ['as' => 'products.store', 'uses' => 'ProductsController@store']);
        Route::put('products/update/{id}', ['as' => 'products.update', 'uses' => 'ProductsController@update']);
        Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'ProductsController@destroy']);
        //**ORDERS**//
        Route::get('orders', ['as' => 'orders.index', 'uses' => 'OrdersController@index']);
        Route::get('orders/edit/{id}', ['as' => 'orders.edit', 'uses' => 'OrdersController@edit']);
        Route::put('orders/update/{id}', ['as' => 'orders.update', 'uses' => 'OrdersController@update']);
        //**CUPOMS**//
        Route::get('cupoms', ['as' => 'cupoms.index', 'uses' => 'CupomsController@index']);
        Route::get('cupoms/create', ['as' => 'cupoms.create', 'uses' => 'CupomsController@create']);
        Route::post('cupoms/store', ['as' => 'cupoms.store', 'uses' => 'CupomsController@store']);
    });
    //**ORDER**//
    Route::group(['prefix' => 'customer', 'middleware' => 'auth.checkrole:client', 'as' => 'customer.'], function () {
        Route::get('order', ['as' => 'order.index', 'uses' => 'CheckoutController@index']);
        Route::get('order/create', ['as' => 'order.create', 'uses' => 'CheckoutController@create']);
        Route::post('order/store', ['as' => 'order.store', 'uses' => 'CheckoutController@store']);
    });

    //**OAUTH**//
    Route::post('oauth/access_token', function () {
        return Response::json(Authorizer::issueAccessToken());
    });

    Route::group(['prefix' => 'api', 'middleware' => 'oauth', 'as' => 'api.'], function () {

        Route::get('teste',  function () {
            return 'rota api teste';
        });

        Route::group(['prefix' => 'client', 'middleware' => 'oauth.checkrole:client', 'as' => 'client.'], function () {
            Route::resource('order', 'Api\Client\ClientCheckoutController', ['except' => ['create', 'edit', 'destroy']]);
        });
        Route::group(['prefix' => 'deliveryman', 'middleware' => 'oauth.checkrole:deliverymen', 'as' => 'deliveryman.'], function () {
            Route::resource('order', 'Api\Deliveryman\DeliverymanCheckoutController', ['except' => ['create', 'edit', 'destroy', 'store']]);
            Route::patch('order/{id}/update-status', ['as' => 'orders.update_status', 'uses' => 'Api\Deliveryman\DeliverymanCheckoutController@updateStatus']);
        });
    });
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>CodeDelivery</title>

    <!-- Fonts -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet'
          type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel='stylesheet' type='text/css'>

    <!-- Styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ url('/') }}">
                CodeDelivery
            </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            <ul class="nav navbar-nav">
                <li><a href="{{ url('/home') }}">Home</a></li>
                @if(Auth::user())
                    @if(Auth::user()->role == "admin")
                    <li><a href="{{ route('admin.categories.index') }}">Categorias</a></li>
                    <li><a href="{{ route('admin.products.index') }}">Produtos</a></li>
                    <li><a href="{{ route('admin.clients.index') }}">Clientes</a></li>
                    <li><a href="{{ route('admin.cupoms.index') }}">Cupons</a></li>
                    <li><a href="{{ route('admin.orders.index') }}">Pedidos</a></li>
                    @elseif(Auth::user()->role == "client")
                        <li><a href="{{route('customer.order.index')}}">Meus pedidos</a></li>
                    @endif
                @endif
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                @if (Auth::guest())
                    <li><a href="{{ url('/login') }}">Login</a></li>
                    <li><a href="{{ url('/register') }}">Register</a></li>
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>

@yield('content')

        <!-- JavaScripts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
{{-- <script src="{{ elixir('js/app.js') }}"></script> --}}

@yield('post-script')
</body>
</html>